# entries in this file override toe global DNS
#
# Example blocking email going out to example.com
#
#	local-data: "example.com. 3600 IN MX 5 127.0.0.1"
#	local-data: "example.com. 3600 IN A 127.0.0.1"

# This can also be done dynamically using: unbound-control local-data [...]

# For more complicated redirection, use conf.d/ with stub-add: or forward-add:

local-data: "unbound-1.brakebills.io IN A 10.1.30.8"
local-data: "compute0.ocp4.brakebills.io IN A 10.1.30.11"
local-data: "compute1.ocp4.brakebills.io IN A 10.1.30.13"
local-data: "master0.ocp4.brakebills.io IN A 10.1.30.2"
local-data: "master1.ocp4.brakebills.io IN A 10.1.30.5"
local-data: "master2.ocp4.brakebills.io IN A 10.1.30.7"
local-data: "api.ocp4.brakebills.io IN A 10.1.30.100"
local-data: "api-int.ocp4.brakebills.io IN A 10.1.30.100"
local-zone: "apps.ocp4.brakebills.io" redirect
local-data: "apps.ocp4.brakebills.io 86400 IN A 10.1.30.100"
local-data: "compute2.ocp4.brakebills.io IN A 10.1.30.10"
local-data: "compute3.ocp4.brakebills.io IN A 10.1.30.14"

local-data-ptr: "10.1.30.8 unbound-1.brakebills.io"
local-data-ptr: "10.1.30.11 compute0.ocp4.brakebills.io"
local-data-ptr: "10.1.30.13 compute1.ocp4.brakebills.io"
local-data-ptr: "10.1.30.2 master0.ocp4.brakebills.io"
local-data-ptr: "10.1.30.5 master1.ocp4.brakebills.io"
local-data-ptr: "10.1.30.7 master2.ocp4.brakebills.io"
local-data-ptr: "10.1.30.100 api.ocp4.brakebills.io"
local-data-ptr: "10.1.30.100 api-int.ocp4.brakebills.io"
local-data-ptr: "10.1.30.10 compute2.ocp4.brakebills.io"
local-data-ptr: "10.1.30.14 compute3.ocp4.brakebills.io"

